language: elixir
elixir:
  - '1.7.4'
otp_release:
  - '21.1'

jobs:
  include:
    - stage: "Formatter"
      name: "Formatter"
      script: mix format --check-formatted --check-equivalent
    - stage: "Tests"
      name: "Unit Tests"
      script: mix test
